ARG ENV_REPOSITORY=pawr/pawr-env
FROM ${ENV_REPOSITORY}:base

RUN apt-get update -qq && apt-get install -yqq \
git \
libboost-all-dev

ARG REPOSITORY=pawr-project/pawr-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
